### PR TITLE
Fun stuff

### PR DESCRIPTION
**Pull request by 3kh0**
Merge pls :D

### CODE REVIEW

**Comment by 3kh0** [comment]
@Olivem1234567 Disable signed commits

**Comment by LiamM-MTCBs** [comment]
oh dang, alright

**Review by LiamM-MTCBs — APPROVED** [review]

**Comment by 3kh0** [comment]
image

**Comment by 3kh0** [comment]
image

Make sure this is off in the branch protection settings

**Comment by LiamM-MTCBs** [comment]
Sadly, I cannot change it I will get Oliver to change it real quick.

**Comment by LiamM-MTCBs** [comment]
He is changing the setting, will merge asap!

**Comment by LiamM-MTCBs** [comment]
Done!

**Comment by ivan-developer-01** [comment]
@3kh0 Signing commits is not so hard :D 

I have it enabled on my Linux Mint

**Comment by 3kh0** [comment]
> @3kh0 Signing commits is not so hard :D
> 
> I have it enabled on my Linux Mint

Doing it on Kali is hard and I am too fucking lazy to do it xD

**Comment by ivan-developer-01** [comment]
> > @3kh0 Signing commits is not so hard :D
> > I have it enabled on my Linux Mint
> 
> Doing it on Kali is hard and I am too fucking lazy to do it xD

Lol

**Pull request merged**
